package com.dia.ismdtoolbackend.controller;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.webmvc.test.autoconfigure.AutoConfigureMockMvc;
import org.springframework.test.context.ActiveProfiles;
import org.springframework.test.context.TestPropertySource;
import org.springframework.test.web.servlet.MockMvc;

import static org.assertj.core.api.Assertions.assertThat;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.get;

/**
 * The generated OpenAPI schema must carry the Převzít 409 body.
 *
 * <p>The FE's types are generated by Orval from this schema, and the conflict report is not a message the
 * FE can ignore — it is the input to the resolution UI (which concepts collide, which canvases hold the
 * competing edits), which the user answers with {@code onConflict}. But the 409 is produced by
 * {@code GlobalExceptionHandler}, and springdoc builds its model by walking controller signatures only:
 * a {@code @RestControllerAdvice} return type reaches the schema ONLY through an explicit
 * {@code @ApiResponse}. Nothing else fails when that annotation is dropped — the endpoint still returns a
 * correct 409, every test still passes, and the types silently vanish from the FE's next generate.
 *
 * <p>Asserting on the schema is therefore the only thing that can catch it. See
 * {@code .planning/codebase/TECH_DEBT.md} — every other non-200 response in the API has this gap.
 */
@SpringBootTest
@AutoConfigureMockMvc(addFilters = false)
@ActiveProfiles("junit")
@TestPropertySource(properties = {
        "springdoc.api-docs.enabled=true",
        // Own H2 instance, per the convention in CorsConfig*Test: the junit profile's shared
        // `testdb` is migrated by whichever context boots first, and a second Liquibase run
        // against it fails on the existing DATABASECHANGELOG table.
        "spring.datasource.url=jdbc:h2:mem:testdb-openapi-conflict;MODE=PostgreSQL;"
                + "DATABASE_TO_LOWER=TRUE;INIT=CREATE SCHEMA IF NOT EXISTS ismd_schema",
        "spring.datasource.username=sa",
        "spring.datasource.password=password",
        "spring.datasource.driver-class-name=org.h2.Driver",
        "spring.jpa.database=h2",
        "spring.liquibase.liquibase-schema=PUBLIC",
        "spring.security.oauth2.client.registration.keycloak.client-id=test-client-id",
        "spring.security.oauth2.client.registration.keycloak.client-secret=test-client-secret",
        "spring.security.oauth2.client.registration.keycloak.provider=keycloak-test",
        "spring.security.oauth2.client.provider.keycloak-test.authorization-uri=http://localhost/auth",
        "spring.security.oauth2.client.provider.keycloak-test.token-uri=http://localhost/token",
        "spring.security.oauth2.client.provider.keycloak-test.user-info-uri=http://localhost/userinfo",
        "spring.security.oauth2.client.provider.keycloak-test.jwk-set-uri=http://localhost/jwks",
        "spring.security.oauth2.client.provider.keycloak-test.user-name-attribute=preferred_username",
        "spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost/jwks"
})
class OpenApiConflictSchemaTest {

    private static final String MATERIALIZE = "/api/diagram/{ontologySlug}/{diagramId}/materialize";

    @Autowired private MockMvc mockMvc;

    private static JsonNode spec;

    @BeforeAll
    static void resetSpec() {
        spec = null;
    }

    private JsonNode spec() throws Exception {
        if (spec == null) {
            String body = mockMvc.perform(get("/v3/api-docs"))
                    .andReturn().getResponse().getContentAsString();
            spec = new ObjectMapper().readTree(body);
        }
        return spec;
    }

    /** The operation must declare the 409 at all — without it Orval generates a 200-only client. */
    @Test
    void materializeDeclaresTheConflictResponse() throws Exception {
        JsonNode responses = spec().path("paths").path(MATERIALIZE).path("post").path("responses");

        assertThat(responses.has("409"))
                .as("Převzít must document its 409 — the FE cannot generate a conflict-resolution "
                        + "UI for a response the schema does not mention")
                .isTrue();
        assertThat(responses.path("409").path("content").fieldNames()).hasNext();
    }

    /**
     * The 409 must resolve to the real report shape, not a bare wrapper. Asserting on the leaf fields is
     * the point: a {@code $ref} that resolves to an empty object would still "declare a 409" while giving
     * Orval nothing to generate.
     */
    @Test
    void theConflictResponseResolvesToTheReportShape() throws Exception {
        JsonNode schemas = spec().path("components").path("schemas");

        assertThat(schemas.has("DiagramConflictDto"))
                .as("the report type itself must be generated")
                .isTrue();

        assertThat(schemas.path("DiagramConflictDto").path("properties").has("conflicts")).isTrue();

        JsonNode conflict = schemas.path("Conflict").path("properties");
        assertThat(conflict.has("conceptIri")).as("which concept collided").isTrue();
        assertThat(conflict.has("mine")).as("this diagram's staged edit").isTrue();
        assertThat(conflict.has("theirs")).as("the competing edits").isTrue();

        JsonNode theirs = schemas.path("Theirs").path("properties");
        assertThat(theirs.has("diagramId")).isTrue();
        assertThat(theirs.has("diagramName"))
                .as("the user must be told WHICH canvas holds the competing edit")
                .isTrue();
        assertThat(theirs.has("pendingEdit")).isTrue();
    }

    /**
     * {@code theirs} is a LIST. A concept can be contested by several sibling diagrams at once, and both
     * resolutions act on every one of them — a schema that typed it as a single object would let the FE
     * render only the first competitor and silently hide the rest.
     */
    @Test
    void theConflictReportModelsMultipleCompetingDiagrams() throws Exception {
        JsonNode theirs = spec().path("components").path("schemas")
                .path("Conflict").path("properties").path("theirs");

        assertThat(theirs.path("type").asText())
                .as("one concept can be staged on many sibling canvases")
                .isEqualTo("array");
        assertThat(theirs.path("items").path("$ref").asText()).endsWith("/Theirs");
    }
}