# Stage environment configuration

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.default_schema=ismd_schema

# Liquibase
spring.liquibase.default-schema=ismd_schema
spring.liquibase.liquibase-schema=ismd_schema

# Jena Fuseki configuration
jena.fuseki.url=http://localhost:3030/stage-dataset

# CORS configuration for stage
cors.allowed-origins=

# NKD SPARQL endpoint
nkd.sparql.endpoint=https://oha02.dia.gov.cz/sparql
nkd.sparql.timeout=10000
