# Stage environment configuration

# Jena Fuseki configuration
jena.fuseki.url=http://localhost:3030/stage-dataset

# CORS configuration for stage
cors.allowed-origins=

# NKD SPARQL endpoint
nkd.sparql.endpoint=https://oha02.dia.gov.cz/sparql
nkd.sparql.timeout=10000
