# Spring Application Configuration
spring.application.name=ismd-tool-backend

# PostgreSQL Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/ismd_tool_db
spring.datasource.username=ismd_user
spring.datasource.password=ismd_password
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate Configuration
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.default_schema=ismd_schema
spring.jpa.database=postgresql

# Liquibase
spring.liquibase.liquibase-schema=ismd_schema

# Server Configuration
server.port=8081

# Logging Configuration
logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
logging.level.com.dia.ismdtoolbackend.utility.analyzer.OntologyAnalyzer=DEBUG
logging.level.com.dia.ismdtoolbackend.service.impl.OntologyUploadServiceImpl=DEBUG
logging.level.com.dia.ismdtoolbackend.service.impl=DEBUG
logging.level.com.dia.ismdtoolbackend.repository.JenaTDB2Repository=DEBUG
logging.level.com.dia.ismdtoolbackend.utility=DEBUG
logging.level.com.dia.ismdtoolbackend.service.search=DEBUG

# Management Endpoints Configuration
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always

# Apache Jena TDB2 Configuration
jena.access.method=http
jena.tdb2.location=./data/tdb2/ismd-tool-dataset
jena.tdb2.dataset-name=ismd-tool-dataset
jena.fuseki.url=http://localhost:3030/ismd-tool-dataset
jena.fuseki.connection-timeout=5000
jena.fuseki.max-concurrent-requests=10
jena.fuseki.semaphore-timeout=30000
jena.fuseki.enabled=true
jena.fuseki.port=3030
jena.fuseki.context-path=/fuseki
jena.fuseki.dataset-endpoint=/ismd
jena.fuseki.admin.user=admin
jena.fuseki.admin.password=admin123

# The issuer URL of your Keycloak server
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/ismd
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

# Optional: client credentials if your app needs to call Keycloak as a client
spring.security.oauth2.client.registration.keycloak.client-id=ismd-app
spring.security.oauth2.client.registration.keycloak.client-secret=secret123
spring.security.oauth2.client.registration.keycloak.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.keycloak.redirect-uri={baseUrl}/login/oauth2/code/keycloak
spring.security.oauth2.client.provider.keycloak.issuer-uri=http://localhost:8080/realms/ismd

# Validator API url
validation.service.url:http://localhost:8080/validujeme

# Ontology containing VIOLATION download settings
validation.rules.enable-ontology-violation-download=false

# NKD SPARQL test endpoint
nkd.sparql.endpoint=https://data.gov.cz/slovn%C3%ADky/sparql
nkd.sparql.timeout=10000